#!/bin/bash
##
# create ubuntu .deb package (according to https://wiki.ubuntu.com/PackagingGuide/Complete )
# (create maintainer gpg key first)
##


# maintainer
export DEBFULLNAME="Daniel Hiepler"
export DEBEMAIL="daniel-ubuntu@niftylight.de"
# repository
REPO="file:///media/GT-5830/code/niftyconf.git"
# debian files
DEBIAN="$(pwd)/debian"
# temporary path
TMP="`pwd`/niftyconf-deb-build"
# package name
PKG_NAME="niftyconf"
# package version
PKG_VERSION="0.0.1"
# dh_make license
LICENSE=gpl3




function die()
{
    echo "Error: $1"
    exit 1
}


if ! test -d "${TMP}" ; then mkdir ${TMP} || die "mkdir" ; fi
DIR="${TMP}/${PKG_NAME}-${PKG_VERSION}"

# clone repo
if test -d "${DIR}" ; then
 cd ${DIR} || die "cd"
 git pull || die "git"
else
 git clone "${REPO}" "${DIR}" || die "git"
 cd ${DIR} || die "cd"
fi

# configure
autoreconf -i || die "autoreconf"

# create debian files
rm -Rf ${DIR}/debian 2>/dev/null
dh_make  --copyright "${LICENSE}" --email "${DEBEMAIL}" --createorig --single || die "dh_make"
cp -r "${DEBIAN}"/* "${DIR}/debian/" || die "debian files copy"

# build source
dpkg-buildpackage -S -v"${PKG_VERSION}" || die "source pkg build"

# build binary
dpkg-buildpackage -b -v"${PKG_VERSION}" || die "binary pkg build"


cd -
#rm -Rf "${DIR}"

echo "Done. All files in \"${TMP}\""
