#!/bin/bash
##
# create ubuntu .deb package (according to https://wiki.ubuntu.com/PackagingGuide/Complete )
# (create maintainer gpg key first)
##


# maintainer
export DEBFULLNAME="Daniel Hiepler"
export DEBEMAIL="daniel-ubuntu@niftylight.de"
# repository
REPO="file:///media/GT-5830/code/niftyconf.git"
# debian files
DEBIAN="$(pwd)/debian"
# temporary path
TMP="/tmp/niftyconf"
# package name
PKG_NAME="niftyconf"
# package version
PKG_VERSION="0.0.1"
# dh_make license
LICENSE=gpl3




function die()
{
    echo "Error: $1"
    exit 1
}


if ! test -d "${TMP}" ; then mkdir ${TMP} || die "mkdir" ; fi
DIR="${TMP}/${PKG_NAME}-${PKG_VERSION}"

# clone repo
git clone --verbose "${REPO}" "${DIR}" || die "git"
cd ${DIR} || die "cd"

# configure
autoreconf -i || die "autoreconf"

# create debian files
rm -Rf ${TMP}/debian 2>/dev/null
dh_make  --copyright "${LICENSE}" --email "${DEBEMAIL}" --createorig --multi || die "dh_make"
cp -r "${DEBIAN}"/* "${DIR}/debian/" || die "debian files copy"

# build binary
debuild || die "debuild"

# build source
debuild -S || "debuild source"

cd -
rm -Rf "${DIR}"

echo "Done. All files in \"${TMP}\""
